version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: copexit-am-i-exposed_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/copexit/am-i-exposed-umbrel:v0.37.3@sha256:fd59d631b9f49ef6d7bb5120a60ea9dc534783832cf36caf034480005232dc79
    user: "101:101"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
    environment:
      APP_MEMPOOL_IP: ${APP_MEMPOOL_IP}
      APP_MEMPOOL_PORT: ${APP_MEMPOOL_PORT}
      APP_MEMPOOL_HIDDEN_SERVICE: ${APP_MEMPOOL_HIDDEN_SERVICE}
      APP_TOR_PROXY_IP: tor-proxy
      APP_TOR_PROXY_PORT: "3001"
    depends_on:
      - tor-proxy

  tor-proxy:
    image: ghcr.io/copexit/am-i-exposed-tor-proxy:v0.37.3@sha256:dd4224ad4f381a13462d9c63e78cc9bff4868cbe8877d96f74409a07e9c8820e
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 10s
    environment:
      PORT: "3001"
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
