version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: copexit-am-i-exposed_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/copexit/am-i-exposed-umbrel:v0.42.1@sha256:6d7ceb1a7527fb3c846ed2e268570d1b3bdab7f8617fba516c526d281974aea1
    user: "101:101"
    init: true
    restart: on-failure
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
    environment:
      APP_MEMPOOL_IP: ${APP_MEMPOOL_IP}
      APP_MEMPOOL_PORT: ${APP_MEMPOOL_PORT}
      APP_MEMPOOL_HIDDEN_SERVICE: ${APP_MEMPOOL_HIDDEN_SERVICE}
      APP_BITCOIN_NETWORK: ${APP_BITCOIN_NETWORK}
      APP_TOR_PROXY_IP: tor-proxy
      APP_TOR_PROXY_PORT: "3001"
    depends_on:
      - tor-proxy

  tor-proxy:
    image: ghcr.io/copexit/am-i-exposed-tor-proxy:v0.42.1@sha256:8f0ec7e27549ea493215a9c450480ad30366ca8f1397e1b5509b4c37477587ab
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 10s
    environment:
      PORT: "3001"
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
